"""add_extraction_rule_id_to_cloud_folder_sources

Revision ID: 08d252d21666
Revises: 76dd7a0179bf
Create Date: 2026-03-11 15:18:06.939349
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08d252d21666'
down_revision: Union[str, None] = '76dd7a0179bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_str_row_data_gin'), table_name='structured_table_rows', postgresql_using='gin')
    op.drop_index(op.f('idx_str_row_table_id'), table_name='structured_table_rows')
    op.drop_index(op.f('idx_str_row_text_trgm'), table_name='structured_table_rows', postgresql_ops={'row_text': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_str_row_tsvector'), table_name='structured_table_rows', postgresql_using='gin')
    op.drop_table('structured_table_rows')
    op.drop_index(op.f('idx_str_table_category'), table_name='structured_tables')
    op.drop_index(op.f('idx_str_table_content_hash'), table_name='structured_tables')
    op.drop_index(op.f('idx_str_table_keywords'), table_name='structured_tables', postgresql_using='gin')
    op.drop_index(op.f('idx_str_table_owner'), table_name='structured_tables')
    op.drop_index(op.f('idx_str_table_source_type'), table_name='structured_tables')
    op.drop_table('structured_tables')
    op.add_column('cloud_folder_sources', sa.Column('extraction_rule_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('kg_profiles_owner_id_key'), 'kg_profiles', type_='unique')
    op.drop_index(op.f('ix_kg_profiles_owner_id'), table_name='kg_profiles')
    op.create_index(op.f('ix_kg_profiles_owner_id'), 'kg_profiles', ['owner_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kg_profiles_owner_id'), table_name='kg_profiles')
    op.create_index(op.f('ix_kg_profiles_owner_id'), 'kg_profiles', ['owner_id'], unique=False)
    op.create_unique_constraint(op.f('kg_profiles_owner_id_key'), 'kg_profiles', ['owner_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('cloud_folder_sources', 'extraction_rule_id')
    op.create_table('structured_tables',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('source_app_token', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('source_table_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('source_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('file_name', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('schema_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('row_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('column_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('source_platform', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('feishu_record_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('content_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1024), autoincrement=False, nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('sentiment', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('duplicate_of', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('extra_fields', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('parse_status', sa.VARCHAR(length=16), server_default=sa.text("'done'::character varying"), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('table_category', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('cleaning_rule_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.CheckConstraint("parse_status IS NULL OR (parse_status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'done'::character varying, 'failed'::character varying]::text[]))", name=op.f('ck_structured_table_parse_status')),
    sa.CheckConstraint("sentiment IS NULL OR (sentiment::text = ANY (ARRAY['positive'::character varying, 'neutral'::character varying, 'negative'::character varying]::text[]))", name=op.f('ck_structured_table_sentiment')),
    sa.CheckConstraint("source_type::text = ANY (ARRAY['bitable'::character varying, 'spreadsheet'::character varying, 'local'::character varying]::text[])", name=op.f('ck_structured_table_source_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('structured_tables_pkey')),
    sa.UniqueConstraint('owner_id', 'source_app_token', 'source_table_id', name=op.f('uq_structured_table_source'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_str_table_source_type'), 'structured_tables', ['source_type'], unique=False)
    op.create_index(op.f('idx_str_table_owner'), 'structured_tables', ['owner_id'], unique=False)
    op.create_index(op.f('idx_str_table_keywords'), 'structured_tables', ['keywords'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_str_table_content_hash'), 'structured_tables', ['content_hash'], unique=False)
    op.create_index(op.f('idx_str_table_category'), 'structured_tables', ['table_category'], unique=False)
    op.create_table('structured_table_rows',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('table_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('row_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('row_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('row_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['structured_tables.id'], name=op.f('structured_table_rows_table_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('structured_table_rows_pkey'))
    )
    op.create_index(op.f('idx_str_row_tsvector'), 'structured_table_rows', [sa.literal_column("to_tsvector('simple'::regconfig, COALESCE(row_text, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_str_row_text_trgm'), 'structured_table_rows', ['row_text'], unique=False, postgresql_ops={'row_text': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_str_row_table_id'), 'structured_table_rows', ['table_id'], unique=False)
    op.create_index(op.f('idx_str_row_data_gin'), 'structured_table_rows', ['row_data'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
