"""add key_info and extraction_rule_id to structured_tables

Revision ID: 1f1886c130cd
Revises: 28cef6f4fa01
Create Date: 2026-03-18 16:13:55.646238
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f1886c130cd'
down_revision: Union[str, None] = '28cef6f4fa01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('structured_tables', sa.Column('key_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('structured_tables', sa.Column('extraction_rule_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('structured_tables', 'extraction_rule_id')
    op.drop_column('structured_tables', 'key_info')
    # ### end Alembic commands ###
