"""add llm_reason and ingested_record fields to bot_message_tasks

Revision ID: 25c809e13ddc
Revises: b1c2d3e4f5a6
Create Date: 2026-03-13 11:14:42.672602
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25c809e13ddc'
down_revision: Union[str, None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_message_tasks', sa.Column('llm_reason', sa.Text(), nullable=True))
    op.add_column('bot_message_tasks', sa.Column('ingested_record_id', sa.Integer(), nullable=True))
    op.add_column('bot_message_tasks', sa.Column('ingested_record_type', sa.String(length=32), nullable=True))
    op.drop_index(op.f('ix_bot_message_tasks_message_id'), table_name='bot_message_tasks')
    op.create_unique_constraint(None, 'bot_message_tasks', ['message_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bot_message_tasks', type_='unique')
    op.create_index(op.f('ix_bot_message_tasks_message_id'), 'bot_message_tasks', ['message_id'], unique=True)
    op.drop_column('bot_message_tasks', 'ingested_record_type')
    op.drop_column('bot_message_tasks', 'ingested_record_id')
    op.drop_column('bot_message_tasks', 'llm_reason')
    # ### end Alembic commands ###
