"""add_calendar_briefs_table

Revision ID: 37b35a841317
Revises: 0e7ab029f520
Create Date: 2026-03-13 19:40:00.705102
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37b35a841317'
down_revision: Union[str, None] = '0e7ab029f520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_briefs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=256), nullable=False),
    sa.Column('event_summary', sa.String(length=512), server_default='', nullable=False),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('chat_messages', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cal_brief_owner_event', 'calendar_briefs', ['owner_id', 'event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_cal_brief_owner_event', table_name='calendar_briefs')
    op.drop_table('calendar_briefs')
    # ### end Alembic commands ###
