"""add etl_data_sources table

Revision ID: 92851a26d6b0
Revises: df3d57931bd6
Create Date: 2026-02-27 18:35:51.988700
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92851a26d6b0'
down_revision: Union[str, None] = 'df3d57931bd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_data_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_token', sa.String(length=128), nullable=False),
    sa.Column('table_id', sa.String(length=128), nullable=False),
    sa.Column('table_name', sa.String(length=256), server_default='', nullable=False),
    sa.Column('asset_type', sa.String(length=32), server_default='conversation', nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_etl_ds', 'etl_data_sources', ['app_token', 'table_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_etl_ds', table_name='etl_data_sources')
    op.drop_table('etl_data_sources')
    # ### end Alembic commands ###
