"""add uploaded_by to three content tables

Revision ID: 954d33874f3b
Revises: a7q8r9s0t1u2
Create Date: 2026-03-12 18:02:04.722023
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '954d33874f3b'
down_revision: Union[str, None] = 'a7q8r9s0t1u2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communications', sa.Column('uploaded_by', sa.String(length=256), nullable=True))
    op.add_column('documents', sa.Column('uploaded_by', sa.String(length=256), nullable=True))
    op.add_column('structured_tables', sa.Column('uploaded_by', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('structured_tables', 'uploaded_by')
    op.drop_column('documents', 'uploaded_by')
    op.drop_column('communications', 'uploaded_by')
    # ### end Alembic commands ###
