"""add structured_tables and structured_table_rows

Revision ID: c8e804ef9da6
Revises: 08d252d21666
Create Date: 2026-03-11 15:37:09.103906
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'c8e804ef9da6'
down_revision: Union[str, None] = '08d252d21666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('structured_tables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('table_category', sa.String(length=64), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_platform', sa.String(length=32), nullable=True),
    sa.Column('source_app_token', sa.String(length=128), nullable=True),
    sa.Column('source_table_id', sa.String(length=128), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('feishu_record_id', sa.String(length=128), nullable=True),
    sa.Column('file_name', sa.String(length=512), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('schema_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('row_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('column_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content_vector', Vector(1024), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('sentiment', sa.String(length=16), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('duplicate_of', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('cleaning_rule_id', sa.Integer(), nullable=True),
    sa.Column('extra_fields', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('parse_status', sa.String(length=16), server_default='done', nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("parse_status IS NULL OR parse_status IN ('pending', 'processing', 'done', 'failed')", name='ck_structured_table_parse_status'),
    sa.CheckConstraint("sentiment IS NULL OR sentiment IN ('positive', 'neutral', 'negative')", name='ck_structured_table_sentiment'),
    sa.CheckConstraint("source_type IN ('bitable', 'spreadsheet', 'local')", name='ck_structured_table_source_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'source_app_token', 'source_table_id', name='uq_structured_table_source')
    )
    op.create_index('idx_str_table_category', 'structured_tables', ['table_category'], unique=False)
    op.create_index('idx_str_table_content_hash', 'structured_tables', ['content_hash'], unique=False)
    op.create_index('idx_str_table_keywords', 'structured_tables', ['keywords'], unique=False, postgresql_using='gin')
    op.create_index('idx_str_table_owner', 'structured_tables', ['owner_id'], unique=False)
    op.create_index('idx_str_table_source_type', 'structured_tables', ['source_type'], unique=False)
    op.create_table('structured_table_rows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('row_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('row_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['structured_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_str_row_table_id', 'structured_table_rows', ['table_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_str_row_table_id', table_name='structured_table_rows')
    op.drop_table('structured_table_rows')
    op.drop_index('idx_str_table_source_type', table_name='structured_tables')
    op.drop_index('idx_str_table_owner', table_name='structured_tables')
    op.drop_index('idx_str_table_keywords', table_name='structured_tables', postgresql_using='gin')
    op.drop_index('idx_str_table_content_hash', table_name='structured_tables')
    op.drop_index('idx_str_table_category', table_name='structured_tables')
    op.drop_table('structured_tables')
    # ### end Alembic commands ###
