"""init tables

Revision ID: df3d57931bd6
Revises: 
Create Date: 2026-02-26 23:16:43.690081
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'df3d57931bd6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('data_assets',
    sa.Column('feishu_record_id', sa.String(length=128), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('source_app_token', sa.String(length=128), nullable=False),
    sa.Column('source_table_id', sa.String(length=128), nullable=True),
    sa.Column('asset_type', sa.String(length=32), server_default='conversation', nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('content_vector', Vector(1536), nullable=True),
    sa.Column('asset_tags', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('feishu_created_at', sa.DateTime(), nullable=True),
    sa.Column('feishu_updated_at', sa.DateTime(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("asset_type IN ('conversation', 'meeting_note', 'document', 'other')", name='ck_data_assets_type'),
    sa.PrimaryKeyConstraint('feishu_record_id')
    )
    op.create_index('idx_assets_owner', 'data_assets', ['owner_id'], unique=False)
    op.create_index('idx_assets_tags', 'data_assets', ['asset_tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_assets_type', 'data_assets', ['asset_type'], unique=False)
    op.create_table('etl_sync_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_app_token', sa.String(length=128), nullable=False),
    sa.Column('source_table_id', sa.String(length=128), nullable=False),
    sa.Column('last_sync_time', sa.DateTime(), server_default='1970-01-01T00:00:00+00:00', nullable=False),
    sa.Column('last_sync_status', sa.String(length=16), server_default='idle', nullable=False),
    sa.Column('records_synced', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("last_sync_status IN ('idle', 'running', 'success', 'failed')", name='ck_etl_sync_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_etl_sync_source', 'etl_sync_state', ['source_app_token', 'source_table_id'], unique=True)
    op.create_table('schema_mapping_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_app_token', sa.String(length=128), nullable=False),
    sa.Column('source_table_id', sa.String(length=128), nullable=False),
    sa.Column('schema_md5', sa.String(length=32), nullable=False),
    sa.Column('mapping_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_schema_cache', 'schema_mapping_cache', ['source_app_token', 'source_table_id', 'schema_md5'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feishu_open_id', sa.String(length=64), nullable=False),
    sa.Column('feishu_union_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=16), server_default='employee', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('employee', 'executive', 'admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feishu_open_id')
    )
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_role', table_name='users')
    op.drop_table('users')
    op.drop_index('uq_schema_cache', table_name='schema_mapping_cache')
    op.drop_table('schema_mapping_cache')
    op.drop_index('uq_etl_sync_source', table_name='etl_sync_state')
    op.drop_table('etl_sync_state')
    op.drop_index('idx_assets_type', table_name='data_assets')
    op.drop_index('idx_assets_tags', table_name='data_assets', postgresql_using='gin')
    op.drop_index('idx_assets_owner', table_name='data_assets')
    op.drop_table('data_assets')
    # ### end Alembic commands ###
