"""add sheet_name to structured_table_rows

Revision ID: ecd7fdd3d731
Revises: 1f1886c130cd
Create Date: 2026-03-19 00:22:07.734807
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecd7fdd3d731'
down_revision: Union[str, None] = '1f1886c130cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('structured_table_rows', sa.Column('sheet_name', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('structured_table_rows', 'sheet_name')
    # ### end Alembic commands ###
